version: "3.7"

x-default-env: &default-env
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  backend:
    build: ./src/
    ports:
      - "5000:5000"
    volumes:
      - ./src:/opt/project
    command: "flask run --reload -h 0.0.0.0"
    environment:
      PYTHONUNBUFFERED: 1
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}
      <<: *default-env

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  database:
    image: postgres:12
    environment:
      <<: *default-env
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
