"""Relation change

Revision ID: 465eb3a52c1f
Revises: a355c389c76e
Create Date: 2020-11-15 20:35:49.889243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465eb3a52c1f'
down_revision = 'a355c389c76e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_like_user_id_user', 'like', type_='foreignkey')
    op.drop_constraint('fk_like_post_id_post', 'like', type_='foreignkey')
    op.create_foreign_key(op.f('fk_like_user_id_user'), 'like', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_like_post_id_post'), 'like', 'post', ['post_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('fk_post_author_id_user', 'post', type_='foreignkey')
    op.create_foreign_key(op.f('fk_post_author_id_user'), 'post', 'user', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    op.create_unique_constraint(op.f('uq_user_login'), 'user', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_login'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.drop_constraint(op.f('fk_post_author_id_user'), 'post', type_='foreignkey')
    op.create_foreign_key('fk_post_author_id_user', 'post', 'user', ['author_id'], ['id'])
    op.drop_constraint(op.f('fk_like_post_id_post'), 'like', type_='foreignkey')
    op.drop_constraint(op.f('fk_like_user_id_user'), 'like', type_='foreignkey')
    op.create_foreign_key('fk_like_post_id_post', 'like', 'post', ['post_id'], ['id'])
    op.create_foreign_key('fk_like_user_id_user', 'like', 'user', ['user_id'], ['id'])
    op.alter_column('like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
